const menu = [
  {
    id: 1,
    title: "Fish Kabiraji",
    category: "starters",
    price: 485.0,
    img: "./images/item-11.jpg",
    desc: `Fish fillet nestled within a fine, delicate, airy, crunchy web—a classic from the cabins of Kolkata.`,
  },
  {
    id: 2,
    title: "Chingri Malaikari",
    category: "lunch",
    price: 750.0,
    img: "./images/item-12.jpg",
    desc: ` Signature Bengali prawn delicacy prepared with jumbo prawns or Shrimp and coconut milk, along with hot spices.`,
  },
  {
    id: 3,
    title: "Kheer Doi",
    category: "desserts",
    price: 165.0,
    img: "./images/item-13.jpg",
    desc: `All the way from Nabadwip, this rich and creamy dessert is an absolute delicacy.`,
  },
  {
    id: 4,
    title: "Foul Cutlet",
    category: "starters",
    price: 475.0,
    img: "./images/item-14.jpg",
    desc: `Cooked meat stuffing that is fried with a batter, and spices - onion, cardamom, cloves, cinnamon, coriander, green chilies, lemon and salt. `,
  },
  {
    id: 5,
    title: "Bhapa Ilish",
    category: "lunch",
    price: 685.0,
    img: "./images/item-15.jpg",
    desc: `Whole fillet of hilsa, masterfully deboned, marinated with fresh mustard and steam.`,
  },
  {
    id: 6,
    title: "Chutney",
    category: "desserts",
    price: 145.0,
    img: "./images/item-16.jpg",
    desc: `A delicious, sweet and spiced tomato chutney made with dates having the flavors & aroma of panch phoron (Bengali 5 spice mix).`,
  },
  {
    id: 7,
    title: "Kathi Roll",
    category: "starters",
    price: 220.0,
    img: "./images/item-17.jpg",
    desc: `Flaky, egg-based parathas filled with meat chunks/veggies, onions and a pool of sauces and spices.`,
  },
  {
    id: 8,
    title: "Mutton Dak Bangalow",
    category: "lunch",
    price: 565.0,
    img: "./images/item-18.jpg",
    desc: `Goat curry recipe that uses a special blend of spices and also has potatoes cooked in the gravy. `,
  },
  {
    id: 9,
    title: "Chhanar Malpoa",
    category: "desserts",
    price: 165.0,
    img: "./images/item-19.jpeg",
    desc: `Deep-fried, flat roundels of homemade 'cheese' dipped in sugar syrup, served with ice-cream.`,
  },
];
export default menu;
